default:
    trainer: ppo
    batch_size: 256
    beta: 5.0e-3
    buffer_size: 4096
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 512
    lambd: 0.95
    learning_rate: 1.0e-3
    max_steps: 60.0e3
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 1
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1
    use_recurrent: true
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

